In [5]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [8]:
!pip install apyori

Defaulting to user installation because normal site-packages is not writeable
Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py): started
  Building wheel for apyori (setup.py): finished with status 'done'
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5975 sha256=7b690474f78b85cc8d804b6e1bb6f8aedefbc8584c4e6af3fc9829cb561134b2
  Stored in directory: c:\users\ihars\appdata\local\pip\cache\wheels\77\3d\a6\d317a6fb32be58a602b1e8c6b5d6f31f79322da554cad2a5ea
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

  WARNING: The script apyori-run.exe is installed in 'C:\Users\ihars\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [9]:
df=pd.read_csv("Market_Basket_Optimisation.csv",header=None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7501,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil

In [11]:
transactions=[]
for i in range(0,7502):
    transactions.append([str(df.values[i,j]) for j in range(0,20)])

In [13]:
from apyori import apriori 
rules=apriori(transactions=transactions , min_support = 0.003 , min_confidence = 0.2,min_lift=3,min_length=2,max_length=2)

In [17]:
results=list(rules)

In [18]:
results

[RelationRecord(items=frozenset({'light cream', 'chicken'}), support=0.0045321247667288725, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.2905982905982906, lift=4.8445963912630585)]),
 RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.005731804852039456, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30069930069930073, lift=3.791338073691015)]),
 RelationRecord(items=frozenset({'escalope', 'pasta'}), support=0.005865102639296188, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.701438541518302)]),
 RelationRecord(items=frozenset({'fromage blanc', 'honey'}), support=0.0033324446814182885, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.150491569176691)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.015995734470807786, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.292432715130547)]),
 RelationRecord(items=frozenset({'ground beef', 'tomato sauce'}), support=0.005331911490269262, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.37735849056603776, lift=3.8411715009856384)]),
 RelationRecord(items=frozenset({'light cream', 'olive oil'}), support=0.003199146894161557, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820512, lift=3.1088319088319087)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.007997867235403893, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.1146304675716445)]),
 RelationRecord(items=frozenset({'shrimp', 'pasta'}), support=0.005065315915755798, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050848, lift=4.498879525297479)])]

In [19]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

In [20]:
resultsinDataFrame

         Left Hand Side Right Hand Side   Support  Confidence      Lift
0           light cream         chicken  0.004532    0.290598  4.844596
1  mushroom cream sauce        escalope  0.005732    0.300699  3.791338
2                 pasta        escalope  0.005865    0.372881  4.701439
3         fromage blanc           honey  0.003332    0.245098  5.150492
4         herb & pepper     ground beef  0.015996    0.323450  3.292433
5          tomato sauce     ground beef  0.005332    0.377358  3.841172
6           light cream       olive oil  0.003199    0.205128  3.108832
7     whole wheat pasta       olive oil  0.007998    0.271493  4.114630
8                 pasta          shrimp  0.005065    0.322034  4.498880

In [21]:
resultsinDataFrame.nlargest(n=10 , columns = 'Lift')

         Left Hand Side Right Hand Side   Support  Confidence      Lift
3         fromage blanc           honey  0.003332    0.245098  5.150492
0           light cream         chicken  0.004532    0.290598  4.844596
2                 pasta        escalope  0.005865    0.372881  4.701439
8                 pasta          shrimp  0.005065    0.322034  4.498880
7     whole wheat pasta       olive oil  0.007998    0.271493  4.114630
5          tomato sauce     ground beef  0.005332    0.377358  3.841172
1  mushroom cream sauce        escalope  0.005732    0.300699  3.791338
4         herb & pepper     ground beef  0.015996    0.323450  3.292433
6           light cream       olive oil  0.003199    0.205128  3.108832